### ISSUE TITLE
Game freezes when importing from Archidekt

### ISSUE THREAD

**Issue by apachano** [omstrumpf/tts-mtg-importer#27]
When importing a deck from Archidekt, the game freezes while the JSON response is parsed. This does not happen when importing from tapped out.

To isolate the issue I printed the return of the web request in queryDeckArchidekt() on [line 998](https://github.com/omstrumpf/tts-mtg-importer/blob/a204d04bdb23e48e4f40af89d50fb8abfeeebe18/loader.lua#L998) instead of completing the function and the response printed instantly. I tried again to print the JSON results from [line 1014](https://github.com/omstrumpf/tts-mtg-importer/blob/a204d04bdb23e48e4f40af89d50fb8abfeeebe18/loader.lua#L1014) and the freeze occurs.

When this freeze happens in multiplayer, the game freezes long enough that all non-host players are kicked.

**Comment by omstrumpf** [comment]
Fixed by #28 !
